"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

exec(open('Duskr/_version.py').read())

print "version : " + __version__

APP = ['Duskr/Duskr.py']
DATA_FILES = [
    ('images', ['images/logo.gif']),
    ('settings', ['settings/settings.ini']),
    ('text', glob.glob('text/*.txt')),
    ('lib/natives', glob.glob('lib/natives/*')),

]

OPTIONS = {
    'iconfile':'images/icon.icns',
    'argv_emulation': True#,
    #'frameworks' : glob.glob('./lib/natives/*')
}

setup(
    name='Duskr',
    version='0.01',
    url='https://github.com/jonathanlurie/Duskr',
    author='Jonathan Lurie',
    author_email='lurie.jo@gmail.com',
    description='Raw development setting interpolator for timelapse sequence.',
    license='LGPL',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
