"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Duskr/Duskr.py']
DATA_FILES = [
    ('images', ['images/logo.gif']),
    ('settings', ['settings/settings.ini']),
    ('extbin', ['extbin/exiv2'])

]

OPTIONS = {
    'iconfile':'images/icon.icns',
    'argv_emulation': True
}

setup(
    name='Duskr',
    version='0.01',
    url='https://github.com/jonathanlurie/Duskr',
    author='Jonathan Lurie',
    author_email='lurie.jo@gmail.com',
    description='Raw picture setting interpolator for timelapse sequence.',
    licence='LGPL',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
